version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kathmandu
    volumes:
      - /filerun/db:/var/lib/mysql

  web:
    image: filerun:arm64v8 #not on docker hub, made with the dockerfile
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_mysql_database
      FR_DB_USER: your_mysql_username
      FR_DB_PASS: your_mysql_password
#      APACHE_RUN_USER: pi
#      APACHE_RUN_USER_ID: 1000
#      APACHE_RUN_GROUP: pi
#      APACHE_RUN_GROUP_ID: 1000
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "80:80"
    volumes:
      - /opt/docker/appdata/filerun/html:/var/www/html
      - /opt/docker/appdata/filerun/user-files:/user-files
